import { randomUUID } from "node:crypto";
import { isUniqueViolation, query, queryOne, transaction, violatedConstraint } from "../db";
import { PAYMENT_WINDOW_MINUTES } from "./config";

/**
 * Colour reservation: the step where a community's chosen colour starts
 * existing before any money moves.
 *
 * A `war_tokens` row and its `entry_orders` row are opened together, inside
 * one transaction, and every failure mode this module reports is a real
 * constraint the database is enforcing, not an application-level guess:
 *
 * - `colour_taken` / `already_entered` — a violation of one of migration
 *   001's two partial unique indexes (`war_tokens_colour_live`,
 *   `war_tokens_contract_live`), both `WHERE status <> 'released'`. Only a
 *   `released` reservation ever frees anything; a `removed` token's colour is
 *   retired for the rest of the war because pixels were already painted in
 *   it. This module never pre-checks either index with a SELECT — two
 *   concurrent callers would both read "free" and both proceed — it inserts
 *   and lets the constraint decide, then translates the violation by
 *   constraint name.
 * - `war_full` — the war's own `max_tokens` cap. Unlike colour and contract,
 *   there is no index behind this one, so a WHERE clause inside the INSERT
 *   is not on its own race-safe — two concurrent inserts for two different
 *   colours can each see the same pre-race count under READ COMMITTED. The
 *   war row is locked with `FOR UPDATE` for the length of the transaction so
 *   the count this check reads is always the true one.
 * - `war_closed` — the war has ended (by status or by its own clock), was
 *   cancelled, or is still a draft.
 */

export type OrderStatus = "pending" | "paid" | "expired" | "failed";

export type Order = {
  id: string;
  warId: string;
  warTokenId: string;
  /**
   * What this order asks for, in lamports. Snapshotted at creation: the price
   * is configuration and it moves, so an order says what it asked rather than
   * what the war currently asks.
   */
  amountLamports: bigint;
  /**
   * The dollar figure this order was recorded with. NOT a price anybody is
   * charged since migration 015 — kept because `amount_usd` is still NOT NULL
   * and because orders placed before the change are the record of what those
   * payers were actually asked for.
   */
  amountUsd: number;
  payerPubkey: string | null;
  referencePubkey: string;
  ipHash: string | null;
  status: OrderStatus;
  failureReason: string | null;
  createdAt: Date;
  expiresAt: Date;
  paidAt: Date | null;
};

export type CreateOrderInput = {
  warId: string;
  chainId: string;
  contract: string;
  /** Normalised contract identity (lowercased for EVM). Task 5's concern; this module only stores it. */
  contractKey: string;
  /**
   * NO COLOUR. Since the flag stopped being something a payer chooses, the
   * slot is assigned by this function — the lowest free one — and there is
   * nothing for a caller to pass or to get wrong. See the INSERT below.
   */
  name: string;
  ticker: string;
  logoUrl?: string | null;
  links?: Record<string, unknown>;
  /**
   * Solana Pay reference public key. Generated by the caller (the route),
   * never here: minting the keypair is crypto material a store function
   * cannot be tested against without mocking randomness.
   */
  referencePubkey: string;
  payerPubkey?: string | null;
  ipHash?: string | null;
};

export type CreateOrderFailureReason =
  | "colour_taken"
  | "already_entered"
  | "war_full"
  | "war_closed"
  | "no_price";

export type CreateOrderResult =
  | { ok: true; order: Order }
  | { ok: false; reason: CreateOrderFailureReason };

type OrderRow = {
  id: string;
  war_id: string;
  war_token_id: string;
  amount_usd: number;
  amount_lamports: string | null;
  payer_pubkey: string | null;
  reference_pubkey: string;
  ip_hash: string | null;
  status: OrderStatus;
  failure_reason: string | null;
  created_at: Date;
  expires_at: Date;
  paid_at: Date | null;
};

const ORDER_COLUMNS = `id, war_id, war_token_id, amount_usd, amount_lamports, payer_pubkey,
  reference_pubkey, ip_hash, status, failure_reason, created_at, expires_at, paid_at`;

function toOrder(row: OrderRow): Order {
  return {
    id: row.id,
    warId: row.war_id,
    warTokenId: row.war_token_id,
    // Zero for an order placed before migration 015. Such an order can no
    // longer be paid — the verifier compares against lamports and nothing
    // clears a floor of zero by arriving — and `POST /api/orders` refuses to
    // create another one against a war with no SOL price.
    amountLamports: BigInt(row.amount_lamports ?? 0),
    amountUsd: row.amount_usd,
    payerPubkey: row.payer_pubkey,
    referencePubkey: row.reference_pubkey,
    ipHash: row.ip_hash,
    status: row.status,
    failureReason: row.failure_reason,
    createdAt: row.created_at,
    expiresAt: row.expires_at,
    paidAt: row.paid_at,
  };
}

export async function orderById(id: string): Promise<Order | null> {
  const row = await queryOne<OrderRow>(
    `SELECT ${ORDER_COLUMNS} FROM entry_orders WHERE id = $1`,
    [id],
  );
  return row ? toOrder(row) : null;
}

/**
 * Reserves a colour and opens the order that will pay for it.
 *
 * Everything that decides whether this succeeds happens inside one
 * transaction and, for the two things a unique index can arbitrate, inside
 * one INSERT: two callers racing for the same colour or the same token both
 * run this function concurrently, and exactly one of them gets a row back.
 * The loser's failure reason comes from which constraint Postgres names, not
 * from anything this function decided in advance.
 */
export async function createOrder(input: CreateOrderInput): Promise<CreateOrderResult> {
  // Expiry runs here, not in the route, for the same reason `currentWar()`
  // advances a war's state itself rather than trusting its callers to: a
  // payer must never be refused a colour that only a dead reservation is
  // holding, and that is not a promise a route can be relied on to remember
  // to keep. A reservation whose window has closed has no claim on anything;
  // if it is still sitting in the table when the INSERT below runs, the
  // partial unique index does its job perfectly and produces the wrong
  // answer — `colour_taken` for a colour nobody holds.
  //
  // Deliberately BEFORE `transaction(`, never inside the callback.
  // `expireStaleOrders` opens a transaction of its own, and `db.ts`'s
  // `transaction()` takes a fresh pooled client per call — so calling it from
  // inside this one would have that second connection wait on row locks this
  // transaction holds and will not release until the call it is waiting on
  // returns. Out here there is no lock held yet and nothing to deadlock
  // against.
  await expireStaleOrders();

  return transaction(async (client) => {
    // FOR UPDATE: the colour and contract races are safe without this —
    // each is decided by a partial unique index, so two concurrent inserts
    // can only ever produce one winner no matter what either transaction
    // saw beforehand. Capacity has no index behind it. A plain `WHERE
    // count(*) < max_tokens` inside the INSERT below is still just a read
    // followed by a write from Postgres's point of view: under READ
    // COMMITTED (this project's default and Postgres's), two concurrent
    // createOrder calls for two DIFFERENT colours each take their own
    // snapshot, each see the same pre-race count, and both pass the check —
    // a war with max_tokens = 1 can end up seating two. Locking this war row
    // for the length of the transaction serialises order creation on it, so
    // the second caller's count query blocks until the first has committed
    // (or rolled back) and then sees the true, post-insert count. Order
    // creation happens at most twenty-four times per war, so this costs
    // nothing.
    const warRow = await client.query<{
      status: string;
      ended: boolean;
      entry_price_usd: number;
      entry_price_sol: string | null;
      max_tokens: number;
    }>(
      `SELECT status, (ends_at <= now()) AS ended, entry_price_usd, entry_price_sol, max_tokens
         FROM wars WHERE id = $1 FOR UPDATE`,
      [input.warId],
    );
    const war = warRow.rows[0];
    if (
      !war ||
      war.ended ||
      war.status === "ended" ||
      war.status === "cancelled" ||
      war.status === "draft"
    ) {
      // 'draft' is an operator's unpublished war: there is no page a payer
      // could see it from, so taking money against it risks owing a refund
      // for a war that never runs. 'scheduled' is deliberately NOT refused
      // here — entry opens before a war starts.
      return { ok: false as const, reason: "war_closed" as const };
    }

    // A war with no SOL price cannot take money. Refused rather than defaulted
    // to zero: a free entry is a decision nobody made, and migration 015 left
    // the column nullable precisely so this case is visible instead of
    // silently priced.
    if (war.entry_price_sol === null) {
      return { ok: false as const, reason: "no_price" as const };
    }

    const tokenId = randomUUID();

    // The capacity check lives in this INSERT's own WHERE clause, evaluated
    // as part of the same statement as the row it would add, rather than as
    // a separate SELECT beforehand that a concurrent insert could invalidate
    // between the read and the write. A token counts against capacity
    // whenever it is not 'released' — the same predicate the two partial
    // unique indexes use, and for the same reason: a 'removed' token's slot
    // is gone for the rest of the war, so it still occupies a seat. This is
    // made race-safe by the FOR UPDATE above, not by anything in the WHERE
    // clause itself — see the comment there.
    let insertResult;
    try {
      insertResult = await client.query<{ id: string }>(
        `INSERT INTO war_tokens
           (id, war_id, chain_id, contract, contract_key, colour_slot, status,
            name, ticker, logo_url, links, metadata_fetched_at, reserved_at)
         SELECT $1, $2, $3, $4, $5,
                (
                  -- THE FLAG IS ASSIGNED, NOT CHOSEN. The lowest slot this war
                  -- has not already given out, computed inside the same
                  -- statement that takes it. The war row is locked FOR UPDATE
                  -- above, so order creation is serialised on it and two
                  -- callers cannot be handed the same number; the partial
                  -- unique index war_tokens_colour_live is still there as the
                  -- thing that would refuse it if they were. (No backticks in
                  -- this comment on purpose: it lives inside a template
                  -- literal, and one would end the string.)
                  SELECT slot FROM generate_series(1, $11) AS slot
                   WHERE slot NOT IN (
                     SELECT colour_slot FROM war_tokens
                      WHERE war_id = $2 AND status <> 'released'
                   )
                   ORDER BY slot LIMIT 1
                ),
                'reserved', $6, $7, $8, $9::jsonb, now(), now()
          WHERE (
            SELECT count(*) FROM war_tokens wt
             WHERE wt.war_id = $2 AND wt.status <> 'released'
          ) < $10
         RETURNING id`,
        [
          tokenId,
          input.warId,
          input.chainId,
          input.contract,
          input.contractKey,
          input.name,
          input.ticker,
          input.logoUrl ?? null,
          JSON.stringify(input.links ?? {}),
          war.max_tokens,
          war.max_tokens,
        ],
      );
    } catch (error) {
      if (isUniqueViolation(error)) {
        const constraint = violatedConstraint(error);
        if (constraint === "war_tokens_colour_live") {
          return { ok: false as const, reason: "colour_taken" as const };
        }
        if (constraint === "war_tokens_contract_live") {
          return { ok: false as const, reason: "already_entered" as const };
        }
      }
      throw error;
    }

    if (insertResult.rowCount === 0) {
      return { ok: false as const, reason: "war_full" as const };
    }

    const orderId = randomUUID();
    const orderRow = await client.query<OrderRow>(
      `INSERT INTO entry_orders
         (id, war_id, war_token_id, amount_usd, amount_lamports, payer_pubkey,
          reference_pubkey, ip_hash, status, created_at, expires_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending', now(),
               now() + ($9 || ' minutes')::interval)
       RETURNING ${ORDER_COLUMNS}`,
      [
        orderId,
        input.warId,
        tokenId,
        // Record-keeping only — `amount_usd` is still NOT NULL and its CHECK
        // refuses zero. What the payer is charged is the lamports beside it.
        war.entry_price_usd,
        war.entry_price_sol,
        input.payerPubkey ?? null,
        input.referencePubkey,
        input.ipHash ?? null,
        String(PAYMENT_WINDOW_MINUTES),
      ],
    );

    return { ok: true as const, order: toOrder(orderRow.rows[0]) };
  });
}

/**
 * Expires every reservation whose payment window has closed unpaid, and
 * frees the colour each one held.
 *
 * Two statements, not one, but both are plain unconditional filters — no
 * caller is racing this on the same row in a way a unique index would need
 * to arbitrate, so a straightforward "what is due" followed by "release
 * what is still reserved" is enough. The second UPDATE is guarded on
 * `status = 'reserved'`: a token whose order timed out but that was, by
 * some other path, no longer just a reservation is left alone rather than
 * force-released.
 */
export async function expireStaleOrders(): Promise<number> {
  return transaction(async (client) => {
    const expired = await client.query<{ id: string; war_token_id: string }>(
      `UPDATE entry_orders
          SET status = 'expired'
        WHERE status = 'pending' AND expires_at <= now()
        RETURNING id, war_token_id`,
    );

    if (expired.rowCount === 0) return 0;

    const tokenIds = expired.rows.map((row) => row.war_token_id);
    await client.query(
      `UPDATE war_tokens
          SET status = 'released', released_at = now(), released_reason = 'order_expired'
        WHERE id = ANY($1::text[]) AND status = 'reserved'`,
      [tokenIds],
    );

    return expired.rowCount ?? 0;
  });
}

/**
 * Colour slots this war has no live claim on: not held by a reservation, an
 * active token, or a removed token's retirement.
 *
 * Used to tell a payer who missed their window, or whose colour was taken
 * out from under them, what is still available (spec §5's "offered the
 * remaining free colours").
 */
export async function freeColours(warId: string): Promise<number[]> {
  // A colour still held by a reservation that timed out is a colour this
  // function would report as taken, to a payer who is being shown this list
  // precisely because they are looking for one that is not. Expiring first
  // makes the answer true at the moment it is given. Same argument as
  // `currentWar()`'s: it happens here rather than in the caller so that no
  // route can forget to do it.
  //
  // Safe to call from here: this function is pool-backed and holds no
  // transaction of its own, so `expireStaleOrders`'s transaction has nothing
  // to contend with. The in-transaction case is a different function —
  // `settle.ts`'s `freeColoursOnClient`, which deliberately reads through
  // the caller's own client and must NOT gain an expiry call.
  await expireStaleOrders();

  const war = await queryOne<{ max_tokens: number }>(
    `SELECT max_tokens FROM wars WHERE id = $1`,
    [warId],
  );
  if (!war) return [];

  const taken = await query<{ colour_slot: number }>(
    `SELECT colour_slot FROM war_tokens WHERE war_id = $1 AND status <> 'released'`,
    [warId],
  );
  const takenSlots = new Set(taken.map((row) => row.colour_slot));

  const free: number[] = [];
  for (let slot = 1; slot <= war.max_tokens; slot++) {
    if (!takenSlots.has(slot)) free.push(slot);
  }
  return free;
}
